### ISSUE TITLE
Is this allowing you to see your grades that they decided to block?

### ISSUE THREAD

**Issue by ETCG** [DeadMansMarch/Schoology-Grader#1]

**Comment by DeadMansMarch** [comment]
Yes. When they don't show your official grade, this calculates it.

**Comment by ETCG** [comment]
Lol nice. Is it a chrome extension or something?

**Comment by DeadMansMarch** [comment]
No you just use tampermonkey or run the script in console. It was just bugging me.

**Comment by ETCG** [comment]
Ahh alright. That's cool!

You honestly thought it was with your time to make that? Lol

**Comment by DeadMansMarch** [comment]
Worth an hour or two to always know my grade, yea.

**Comment by ETCG** [comment]
Oh lol

**Comment by ETCG** [comment]
ill close this since there isnt actually an issue
